--HOW TO CREATE A DATABASE
CREATE DATABASE STUDENT_GRADE
;
--HOW TO USE A DATABASE 
USE STUDENT_GRADE
;

--HOW TO CREATE A TABLE
CREATE TABLE [SCORE_REC](
[ID] [int] NOT NULL,
[NAME] [VARCHAR](50) NULL,
[SCORE] [int] NULL,
)

--HOW TO LOAD DATA INTO A TABLE 
INSERT INTO SCORE_REC
(ID,[NAME],SCORE)
VALUES (1,'SIMISOLA','60'),
      (2, 'IVAN','80'),
	  (3,'METODIJA','52'),
	  (4,'CALLUM','98'),
	  (5,'LEIA','84'),
      (6,'APARECIDA','82'),
	(7,'URSULA','69'),     
	 (8,'RAMAZAN','78'),
	( 9,'CORONA','87'),
	 (10,'ALISE','57'),
	 (11,'GALADRIEL','89'),
	 (12,'MEREL','99'),
	 (13,'CHERICE','55'),
	 (14,'NITHYA','81'),
	 (15,'ELSAD','71'),
	 (16,'LIISI','90'),
	 (17,'JOHANNA','90'),
	 (18,'ANFISA','90'),
	 (19,'RYOSUKE','97'),
	 (20,'SAKCHAI','61'),
	 (21,'ELBERT','63'),
	 (22,'KATELYN','51'),
	 (23,'michael','61')
	 
	 SELECT *
	 FROM SCORE_REC

SELECT*,
ID,
NAME,
SCORE,
CASE WHEN SCORE >= 94 THEN 'A'
--WHEN SCORE IN (90)THEN 'A-'  
WHEN SCORE BETWEEN 88 AND 90 THEN 'A-'
-- WHEN SCORE  IN (87)THEN 'B+'
WHEN SCORE BETWEEN 84 AND 87 THEN 'B+'
--WHEN SCORE IN ( 83)THEN 'B'
WHEN SCORE BETWEEN 81 AND 83 THEN 'B'
 WHEN SCORE IN (80)THEN 'B-'
--WHEN SCORE IN (77)THEN 'C+'
WHEN SCORE >=74 AND SCORE <=78 THEN 'C+'
--WHEN SCORE IN (73)THEN 'C'
WHEN SCORE BETWEEN 71 AND 73 THEN 'C'
WHEN SCORE IN (70)THEN 'C-'
--WHEN SCORE IN ( 67)THEN 'D+'
WHEN SCORE BETWEEN 61 AND 69 THEN 'D+'
--WHEN SCORE IN (60) THEN 'D'
WHEN SCORE BETWEEN 58 AND 60 THEN 'D'
 --WHEN SCORE BETWEEN 51 AND 57 THEN 'F'
 --WHEN SCORE >= 51 AND SCORE <= 57 THEN 'F'
 WHEN SCORE IN (51,52,55,57) THEN 'F'
 ELSE 'NOGRADE' 
 END AS GRADE
 FROM SCORE_REC

 SELECT*,
 SCORE,
 CASE WHEN SCORE >= 60 THEN 'PASSED'  ELSE 'FAILED'
 END AS RESULT
 FROM SCORE_REC



SELECT 
  COUNT(CASE WHEN SCORE >=60 THEN SCORE  END) AS 'PASSED',
  COUNT ( CASE WHEN SCORE <=59 THEN SCORE END ) AS 'FAILED'
FROM SCORE_REC

SELECT RESULT, COUNT (SCORE) AS NUMBER_OF_STUDENT
FROM (
SELECT
 SCORE,
 CASE WHEN SCORE >= 60 THEN 'PASSED'  ELSE 'FAILED'
 END AS RESULT
 FROM SCORE_REC
 ORDER BY 2 DESC
 )G
 GROUP BY RESULT ORDER BY 1 DESC

 --HOW TO GET THE LOWEST SCORE 
 SELECT*
 FROM SCORE_REC
 WHERE SCORE =
 (
 SELECT MAX (SCORE)
 FROM
 SCORE_REC
 )

 SELECT*
 FROM SCORE_REC
 WHERE SCORE = 84




ALTER TABLE SCORE_REC
ALTER COLUMN SCORE [int] NULL


	